spring:
  profiles:
    active:
    - dev # 默认使用环境是 dev
---
server:
  port: 8002
spring:
  application:
    name: LOGIN-PROVIDERs
  profiles: dev # 默认环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8002
spring:
  application:
    name: LOGIN-PROVIDERs
  profiles: test # 默认环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/