spring:
  profiles:
    active:
      - dev # 默认使用环境是 dev
---
server:
  port: 2333
spring:
  application:
    name: REDIS-PROVIDER
  profiles: dev # 默认环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 2333
spring:
  application:
    name: REDIS-PROVIDER
  profiles: test # 测试环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/